LABELS = {
    "en": {
        "ingredients": "Ingredients",
        "instructions": "Instructions",
        "nutrition_summary": "Nutrition summary",
        "energy": "Energy",
        "protein": "Protein",
        "carbs": "Carbs",
        "fat": "Fat",
        "fibre": "Fibre",
        "client": "Client",
        "target_energy": "Total target energy (kJ)",
        "current_kj": "Current (kJ)",
        "target_kj": "Target (kJ)",
        "category": "Category",
        "recipes": "Recipes",
        "scale": "Scale selected recipes",
        "export_title": "MealPlan Pro Export",
        "preview_title": "Scaled recipes (preview)",
    },
    "cs": {
        "ingredients": "Suroviny",
        "instructions": "Postup",
        "nutrition_summary": "Výživové hodnoty",
        "energy": "Energie",
        "protein": "Bílkoviny",
        "carbs": "Sacharidy",
        "fat": "Tuky",
        "fibre": "Vláknina",
        "client": "Klient",
        "target_energy": "Cílová energie (kJ)",
        "current_kj": "Aktuální (kJ)",
        "target_kj": "Cílové (kJ)",
        "category": "Kategorie",
        "recipes": "Recepty",
        "scale": "Přepočítat vybrané recepty",
        "export_title": "MealPlan Pro Export",
        "preview_title": "Náhled přepočítaných receptů",
    },
}
